version: "3"
services:
  springbootmongodb:
    image: mongo:latest
    container_name: "springboot-mongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb_1.0
    ports:
      - 8080:8080
    links:
      - springbootmongodb